### ISSUE TITLE
WordPress email Your Site is Experiencing a Technical Issue

### ISSUE THREAD

**Issue by anuggetzz** [JeremyEnglert/JointsWP-CSS#32]
Hi,

Love JointsWP and have been using it for a few years now as my go-to theme.

However, with a recently launched site, I am getting an email saying the site is experiencing technical issues - the website itself seems fine, but the error is pointing to line 32 in /functions/admin.php which is
$limit = $feed->get_item_quantity(5);  

Here are the details:
WordPress version 5.7
Current theme: JointsWP - CSS (version 5.0)
Current plugin:  (version )
PHP version 7.3.26

Error Details
=============
An error of type E_ERROR was caused in line 32 of the file /home/sites/10a/c/c6b572b4fc/public_html/wp-content/themes/goldnuggetdesigns/functions/admin.php. Error message: Uncaught Error: Call to undefined method WP_Error::get_item_quantity() in /home/sites/10a/c/c6b572b4fc/public_html/wp-content/themes/goldnuggetdesigns/functions/admin.php:32
Stack trace:
#0 /home/sites/10a/c/c6b572b4fc/public_html/wp-admin/includes/template.php(1389): joints_rss_dashboard_widget('', Array)
#1 /home/sites/10a/c/c6b572b4fc/public_html/wp-admin/includes/dashboard.php(256): do_meta_boxes(Object(WP_Screen), 'normal', '')
#2 /home/sites/10a/c/c6b572b4fc/public_html/wp-admin/index.php(181): wp_dashboard()
#3 {main}
  thrown

 understand this could be a plugin conflict or similar but any help appreciated

**Comment by chstappert** [comment]
Do you use wpforms? Do you Need the Dashboard RSS function? If not, cut it off in /functions/admin.php
